### ISSUE TITLE
Crate license file

### ISSUE THREAD

**Issue by oscargus** [ekiwi/wellen#19]
While working on reporting licenses for Surfer, I realized that the wellen crate is reported with
```
Copyright (c) [year], [fullname]
```

My *guess* is that the license file in the repo is not included in the crate and therefore, the default BSD-3-license file is used. Probably:
```
include = ["LICENSE"]
```
is required. (`fst-native` seems to include the correct license file.)

**Comment by ekiwi** [comment]
I tried to apply a fix, can you check if things work on your end with version `0.9.16`?

**Comment by oscargus** [comment]
It doesn't seem to work. However, I now get a warning that didn't exist yesterday. So not sure if `cargo about` got stuck in some weird state or if it actually doesn't work...
```
2024-08-07 13:42:43.8200934 +00:00:00 [WARN] the definition for crate/cratesio/wellen/0.9.16 has not been harvested
```

**Comment by ekiwi** [comment]
@oscargus: Can you try version `0.9.18`?

**Comment by oscargus** [comment]
Sure, I also read up a bit and it seems like `cargo about` fetches information from https://clearlydefined.io/ and that new versions/crates may have to be updated. So I've "harvested" the crate there and now wellen has the correct license text. (It may have been correct for .16 as well, but I didn't understand the warning then. Sorry about that.)

Thanks!
