### ISSUE TITLE
Feature request: Get values of parameters without first loading them

### ISSUE THREAD

**Issue by oscargus** [ekiwi/wellen#20]
While working on https://gitlab.com/surfer-project/surfer/-/merge_requests/442 I am now in a state where I got stuck in a multiple mutable borrow scenario that I do not know how to handle.

This could all be avoided if parameters are always loaded. I do not understand enough about the `mut` aspects (I understand what it is, but not the borrow concepts) to say if one possibly can have this lazy loaded on first access. I tried something like that in the MR above, but it just got me into trouble...

The use case is to be able to display the value of the parameter (which shouldn't change, so just a single value must be loaded) in the variable/scope list. Maybe it can be an opt-in or a command that loads all parameters or something? (I can probably implement the latter in Surfer, but I guess it may be more efficient to do it in Wellen?)

**Comment by ekiwi** [comment]
I think this should be easier (not necessarily easy) to solve in Surfer. Surfer uses the advanced API and thus manages the signal loading very manually.

**Comment by oscargus** [comment]
Fair enough, I managed to get a list of all parameters. Just have to figure out how to actually load them (without adding them...).

**Comment by oscargus** [comment]
Thanks! I think the current things is the missing unwrap. (Did mean to close this the last time, so doing it now. May still comment here for additional questions though...)
