### ISSUE TITLE
Issue loading an FST file

### ISSUE THREAD

**Issue by tasgomes** [ekiwi/wellen#21]
I am using the Surfer waveform viewer and the app gets stuck trying to load this FST file: [overlay_tb.zip](https://github.com/user-attachments/files/16706688/overlay_tb.zip)

I reported the issue https://gitlab.com/surfer-project/surfer/-/issues/310#note_2067063155 but @oscargus asked me to report here as he believes this is an issue with the wellen backend.

I am using Surfer v0.3.0-dev.

**Comment by ekiwi** [comment]
Thanks! I will take a look, and you should hear back from me within a week or so.

**Comment by ekiwi** [comment]
This issue should now be resolved in wellen `v0.9.19`. Thanks for reporting!
