### ISSUE TITLE
`find_offset_from_time_table_idx` panics for needle smaller than all indices.

### ISSUE THREAD

**Issue by Rodrigodd** [ekiwi/wellen#3]
Notice this panic when loading some files in [surfer](https://gitlab.com/surfer-project/surfer).

The function is supposed to return the `DataOffset` that is smaller than the needle, but where there is none, the function panics with a subtraction overflow in `upper_idx = mid_idx - 1`, followed by a bound check error if in `--release` mode.

Tried to fix this myself, but I'm not sure what is the expected result in this situation, or if the bug is actually downstream (I also got a headache trying to prove binary-search invariants in my head).

But I at least created this unit test, feel free to copy it if needed:

```rust
    #[test]
    fn test_find_offset_from_time_table_idx() {
        let idxs = vec![1, 1, 1, 2, 4, 4];
        assert_eq!(
            find_offset_from_time_table_idx(&idxs,
            // Not sure what the result should be here. I imagine that this should be None.
            DataOffset {
                start: 0,
                elements: 3,
                time_match: false,
                next_index: NonZeroU32::new(2),
            }
        );
        assert_eq!(
            find_offset_from_time_table_idx(&idxs, 1),
            DataOffset {
                start: 0,
                elements: 3,
                time_match: true,
                next_index: NonZeroU32::new(2),
            }
        );
        assert_eq!(
            find_offset_from_time_table_idx(&idxs, 3),
            DataOffset {
                start: 3,
                elements: 1,
                time_match: false,
                next_index: NonZeroU32::new(4),
            }
        );
        assert_eq!(
            find_offset_from_time_table_idx(&idxs, 4),
            DataOffset {
                start: 4,
                elements: 2,
                time_match: true,
                next_index: None,
            }
        );
        assert_eq!(
            find_offset_from_time_table_idx(&idxs, 5),
            DataOffset {
                start: 4,
                elements: 2,
                time_match: false,
                next_index: None,
            }
        );
    }
```

**Comment by ekiwi** [comment]
Thanks! I will look into this tomorrow!

**Comment by ekiwi** [comment]
Could you also share the file? I am surprised that there are no values at time 0, because most simulators dump a value right at the beginning of simulation.

**Comment by Rodrigodd** [comment]
Oh, I was actually writing a VCD file from my gameboy emulator, and yes, I was not setting a timestamp at 0. I will share it tomorrow.

**Comment by Rodrigodd** [comment]
Here: [trace.zip](https://github.com/ekiwi/wellen/files/14266746/trace.zip)

**Comment by ekiwi** [comment]
Thanks for providing me with the testcase! I am working on a solution.

Could you tell me what exactly you would want Surfer to render for a signal that is only changed at time N, but never set to a value before that? Would you want Surfer to render nothing until the first signal change (A)? Or would you prefer to assume that every signal is initialized to a default (B)?

To illustrate the two options:
```
          time N -----V
A:  Signal:            _|----------------|____
B:  Signal: xxxxxxxxxxx_|----------------|____
```

**Comment by ekiwi** [comment]
Note: GTKWave uses option `B`.

![image](https://github.com/ekiwi/wellen/assets/2456545/2d634f21-a839-4ccb-b023-ef3290c86a68)

In general I feel like option `A` is more principled though.

**Comment by Rodrigodd** [comment]
Good question. When I tested with GTKWave it used option B (you commented about it while I was writing this). But the option A would be more useful in case the start time is very far in the future? (Assuming that "go to start" goes to the first sample). Like if I truncate a trace file to its end, or if use timestamps from the time since UNIX_EPOCH? Not that I expect to do either of them.

But I have no strong preference, fell free to do what is easier/makes more sense.

**Comment by ekiwi** [comment]
I added the necessary requirements in `wellen` to fix this: https://github.com/ekiwi/wellen/blob/eca185794d1702dbdb965da1fd320e0515965446/tests/vcd.rs#L8

Still needs to be addressed in surfer though.

**Comment by ekiwi** [comment]
Fix for Surfer: https://gitlab.com/surfer-project/surfer/-/merge_requests/274

**Comment by ekiwi** [comment]
Should be fixed now! Thanks for the awesome bug report!
