### ISSUE TITLE
.vcd.gz-support

### ISSUE THREAD

**Issue by oscargus** [ekiwi/wellen#31]
Probably others as well, but GHDL has a switch to create this and I bravely stated that Surfer support all of GHDLs output formats... (Which is still sort of correct.)

**Comment by ekiwi** [comment]
Where would you want to extract the VCD data to? If we extract it into memory, we might easily run out of RAM. A temp file?

**Comment by oscargus** [comment]
I'd say RAM. If one runs out of RAM (and has disk space), one can manually unpack it before loading.

**Comment by ekiwi** [comment]
I have been thinking about this more and - honestly - I would prefer if we could handle this in the surfer code instead of wellen.

**Comment by oscargus** [comment]
Sure, no problems!
