### ISSUE TITLE
Time can only increase panic triggered by VCD file

### ISSUE THREAD

**Issue by TheZoq2** [ekiwi/wellen#5]
Someone found an (annoyingly big) VCD file which triggers a panic when loaded with Surfer 

```
The application panicked (crashed).
Message:  Time can only increase!
Location: wellen/src/wavemem.rs:432
```

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
https://liuonline-my.sharepoint.com/personal/frask53_liu_se/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Ffrask53%5Fliu%5Fse%2FDocuments%2Fsurfer%5Fdump%2Fsimulation%5Fdump%5Fsurfer%5Fbug%2Ezip&parent=%2Fpersonal%2Ffrask53%5Fliu%5Fse%2FDocuments%2Fsurfer%5Fdump

FWIW, this also misbehaved in FWB though in a different way
[Bildschirmaufzeichnung_vom_2024-01-17_13-34-41.webm](https://github.com/ekiwi/wellen/assets/5312813/3b79826f-094b-45b0-9989-8047c8fd22e2)

**Comment by ekiwi** [comment]
@TheZoq2 I cannot download the VCD. It is asking me to login.

**Comment by TheZoq2** [comment]
Oops, looks like files in shared directories are not shared by default :thinking: 

Does this work? https://liuonline-my.sharepoint.com/:u:/g/personal/frask53_liu_se/EeyWh-ip3qFNtZMnJwcbV3YBKVxOP7dbNg3zsGra8oj67Q?e=InNsYk

**Comment by ekiwi** [comment]
Thanks! That one worked. I will look into this issue

**Comment by ekiwi** [comment]
OK. Here is what I found: The file is corrupted, i.e. the last time stamp ends in the middle of the number:

```
b0000000000000000000000000000000000000000000011010101011010111010 ]#
10&
#1748342
00&
#1748343
b0000000000000000000000000000000000000000000011010101011010111011 ]#
10&
#1748344
00&
#17483⏎  
```

That causes the time to jump from `1748344` to `17483`.

I will change `wellen` to handle this more gracefully.

**Comment by ekiwi** [comment]
fixed by `wellen` `v0.7.3`. I will make a surfer PR to bump wellen.

**Comment by TheZoq2** [comment]
Thanks!

**Comment by ekiwi** [comment]
@TheZoq2 : https://gitlab.com/surfer-project/surfer/-/merge_requests/285
