### ISSUE TITLE
assertion failed: (lsb as u32) < u32::MAX when loading a fst file

### ISSUE THREAD

**Issue by augustofg** [ekiwi/wellen#9]
I've tried to open an fst waveform file generated with nvc with [surfer](https://gitlab.com/surfer-project/surfer) but it fails with the following assertion:
```
[INFO] Wave source is file
[INFO] Returning from perform work
[TRACE] Parsing startup commands []
[INFO] Starting async task
[INFO] spade-top and spade-state not set, not loading spade translator
[INFO] Applying startup command: LoadWaveformFile("gca-jobs/repos/fofb-ctrl-gw/hdl/testbench/xwb_fofb_shaper_filt/nvc/xwb_fofb_shaper_filt_tb.fst", LoadOptions { keep_variables: false, keep_unavailable: false })
[INFO] Loading a waveform file: gca-jobs/repos/fofb-ctrl-gw/hdl/testbench/xwb_fofb_shaper_filt/nvc/xwb_fofb_shaper_filt_tb.fst
[INFO] Returning from perform work
[INFO] Starting async task
The application panicked (crashed).
Message:  assertion failed: (lsb as u32) < u32::MAX
Location: wellen/src/hierarchy.rs:213
```
The fst file in question is attached below.
[xwb_fofb_shaper_filt_tb.zip](https://github.com/ekiwi/wellen/files/14933236/xwb_fofb_shaper_filt_tb.zip)

**Comment by ekiwi** [comment]
Thanks! I will look into this. Is it ok to include your FST file in our test suite?

**Comment by ekiwi** [comment]
Thanks! This issue should be fixed in `wellen` `v0.9.3`. I am still leaving this open to see if it would be OK to include your file in the test suite.

**Comment by augustofg** [comment]
Hi @ekiwi,

Thank you for the very quick response. You have my permission to include the attached fst file I've provided, it was generated from an open source project ([https://github.com/lnls-dig/fofb-ctrl-gw](https://github.com/lnls-dig/fofb-ctrl-gw))

**Comment by augustofg** [comment]
Thank you @ekiwi !
